poanetwork/blockscout-terraform

bin/infra

A random 5 character alphanumeric string is generated but 8 was mentioned. Cosmetic fix, but this can be confusing for someone.

make README and random generation code consistent

---

README.md

While deploying this script to AWS, I encountered a few issues that I thought should be documented in case others run into similar problems.
Included in these changes were documentation on creating a default `terraform.tfvars` file and also error handling for mismatched variables within `terraform.tfvars` and `main.tfvars` files.

(Fix) Update Readme

---

modules/stack/libexec/init.sh

First request to `aws ssm get-parameters-by-path` may return incomplete set of parameters, returning `NextToken` for additional requests.
Results of all requests are concatenated.

[ssm] get parameters using next token

---

main/variables.tf

Resolves #28 
Ethereum Mainnet will require much larger storage. We will need to adjust when we are ready for testing.

(Fix) Increases default storage to 100GB

---

README.md
bin/infra
modules/stack/libexec/init.sh

Fixes poanetwork/poa-explorer#323
* Install `gcc` to compile NIFs, such as `bcrypt`, during CodeDeploy
* macOS compatibility fixes
* GNU sed is needed on macoS to make `r` option work.
* `LC_ALL=c` to make `tr` work on binary ouput to generate random prefix.

Install gcc to compile NIFs

---

bin/infra

Fixes #38
`prod.secret.exs` requires a 64 character string. The previous 32 character string created an error while trying to navigate to the contract verification page.

(Fix) Change SECRET_KEY_BASE to 64 char

---

modules/stack/libexec/init.sh

Fixes #40
With the merge of the read contract functionality `libtoolize` was needed  for one of the dependencies. After testing the fix, I was able to successfully complete the deployment.
Here is the temporary build with this fix: http://sokab-explorer-sokol-elb-1771258833.us-east-1.elb.amazonaws.com/en

Install Libtool in build script

---

modules/stack/libexec/init.sh

Resolves #37
The "Verify Smart Contract" feature depends on `node` to be installed in the machine because we use the node lib `solc-js` to compile the smart contract code source.
This PR adds the `node` dependency as a global one in the `init.sh` file.

Add 'node' as global dependency

---

README.md
modules/stack/deploy.tf
modules/stack/hosts.tf
modules/stack/outputs.tf
modules/stack/routing.tf
modules/stack/security.tf
modules/stack/subnets.tf

Fixes #45 
This pull request removes the Classic Load Balancer and adds an Application Load Balancer. This update allows the explorer to utilize Websockets. 
This has been successfully tested.

Switch to an Application Load Balancer and remove Classic Load Balancer

---

README.md
main/main.tf
main/variables.tf
modules/stack/config.tf
modules/stack/routing.tf
modules/stack/variables.tf

Fixes #51 
This PR adds a Listener on Port `443` of the Application Load Balancer. 
- Terraform no longer listens on port `80`. For our usage, we need the Load Balancer to listen on port `443`

Adds SSL listener to the Load Balancer

---

README.md
main/main.tf
main/variables.tf
modules/stack/hosts.tf
modules/stack/variables.tf

Fixes #53 
This PR creates a configurable variable to increase the size of the `root_block_device`. By default, this volume is 8GiB but should contain > 100GiB due to `blockscout` not having rotating logs currently. If this variable is not set you should expect to run out of space in 24-48 hours.

Increase the size of root_block_device

---

modules/stack/routing.tf

Fixes #56 
With the removal of internationalization from `blockscout` we need to update the health check of the load balancer from `/en/blocks` to `/blocks` to ensure we're hitting the correct endpoint.

update health check endpoint

---

modules/stack/libexec/init.sh

Fixes #64 
I was unable to deploy all day due to a dependency that is now required in order to install Erlang. Instead of using `rpm -Uvh`, I decided to use `yum install` which will install any needed dependencies.

Fix dependency for libtinfo.so while installing Erlang

---

README.md
bin/infra
main/main.tf
main/variables.tf
modules/stack/routing.tf
modules/stack/variables.tf

Makes ALB listener configurable to allow using both `http` and `https`, removes a new line character from generated variable `secret_key_base` that causes error. Also adds  instruction to  use `json` output format for the AWS CLI, because script generates `key pair` and then queries `KeyMaterial` field from the output, but it will be missed for the `text` format for example.

Configurable ALB listener

---

README.md
main/main.tf
main/variables.tf
modules/stack/config.tf
modules/stack/variables.tf
terraform.tfvars.example

Resolves #59 
This enhancement adds `pool_size`  to the list of configurable variables and also increases the default value from `10` to `30`.

Adds pool size as a configurable variable

---

modules/stack/config.tf

Resolves #68 
This change reflects upcoming changes in https://github.com/poanetwork/blockscout/pull/1006 of `blockscout`. 
- `ethereum_url` -> `ethereum_jsonrpc_http_url`
- `trace_url` -> `ethereum_jsonrpce_trace_url`
- `ws_url` -> `ethereum_jsonrpc_ws_url`
For current infrastructure builds, please update the SSM parameters inside AWS in order to reflect the changes in this PR before deploying. You could also manually enter the endpoints into the build prior to uploading to AWS.

Update Systems Manager variables

---

modules/stack/libexec/init.sh

Adds C compiler tools necessary to build a dependency for poanetwork/blockscout#1028. I'm not sure what the equivalent packages are for yum but here's what is need for debian:
* autoconf
* build-essential
* libgmp3-dev
* libtool

Add C compiler tools

---

group_vars/blockscout.yml.example

This PR fixes #116 and gets back the `terraform_location` variable to `blockscout.yml.example` file that was deleted by accident.

Fix terraform_location variable

---

group_vars/blockscout.yml.example
group_vars/infrastructure.yml.example

Just noted that terraform location variable was set in blockscout example file, while it is related to infra and should be located at infra example file accordingly. Related to #116.

Move terraform variable to correct file

---

roles/main_infra/files/hosts.tf

There is a bug in TF script that lead to the inconsistent changes being made using script. The solution is, according to the Terraform official docs, to delete one of the `availability_zones` or `vpc_zone_identifier` variables.

Remove incompatible variable
